### ISSUE TITLE
How to use it in Vue3

### ISSUE THREAD

**Issue by zhangboyanzhangboyan** [piercus/fake-progress#3]
The page will automatically refresh in Vue2, but not in Vue3

Do I have to use a forced refresh method?

**Comment by piercus** [comment]
Hello,

I'm not an expert on Vue2 or Vue3.

Can you please give more details, what is the scenario ? 

What is the expected? What is the actual? 
Do you have an example code to share ?

**Comment by MrSSai** [comment]
Hi,
You can read this page https://juejin.cn/post/7218828714468786213。Might give you some advice.

**Comment by liuheo** [comment]
> Hi, You can read this page [https://juejin.cn/post/7218828714468786213。Might](https://juejin.cn/post/7218828714468786213%E3%80%82Might) give you some advice.

Thank you very much. That's what you need.

**Comment by liuheo** [comment]
Hi,
You can read this [issuecomment](https://github.com/sunzsh/vue-el-demo/issues/2#issuecomment-1515785677)

**Comment by liuheo** [comment]
你好，我最近正在学习中，无法亲自回复你的邮件。我将尽快给你回复。

**Comment by piercus** [comment]
English please?

**Comment by liuheo** [comment]
> English please?

You can use this in vue3.

```vue
<template>
<el-progress :percentage="parseInt(progressObject.progress * 100)" type="circle" ></el-progress>
<h1>{{ progressObject.progress }}</h1>
<el-button type="primary" @click="progressObject.end()">end</el-button>
</template>
<script setup>
import { reactive} from "vue";
import fakeProgress from "fake-progress";
const progressObject = reactive(
  new fakeProgress({
    timeConstant: 1000,
  })
);
onMounted(() => {
   progressObject.start();
 });
</script>
```
